# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
