# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-06 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theauth', '0002_auto_20190806_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='vet_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
