# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-31 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theauth', '0003_vet_vet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
