# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-31 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theauth', '0004_vet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=254),
        ),
    ]
