# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-31 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theauth', '0007_auto_20190901_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
