# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-20 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('theauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pastoralist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordervets', to='profiles.Profile')),
                ('vet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordervets', to='theauth.Vet')),
            ],
        ),
    ]
