# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVet',
            fields=[
                ('booked_time', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pastoralist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theauth.Pastoralist')),
                ('vet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theauth.Vet')),
            ],
        ),
    ]
