# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-31 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordervet',
            old_name='booked_time',
            new_name='created_at',
        ),
    ]
