# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-24 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordervet',
            name='pastoralist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordervets', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='ordervet',
            name='vet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordervets', to='theauth.Vet'),
        ),
    ]
